### PR TITLE
Fix crash caused by sdg not being hashashable

### PR DESCRIPTION
**Pull request by kayoub5**

### CODE REVIEW

**Comment by andlaus** [comment]
looks good, merging...

**Comment by andlaus** [comment]
BTW: what does "hashashable" mean? something involving THC? ;-P

**Comment by kayoub5** [comment]
> BTW: what does "hashashable" mean? something involving THC? ;-P

hashable means primitive type (int, float, str) or class that impliments `__hash__` function, objects that are hashable are supposed to be immutable (can be used as dict keys)

**Comment by andlaus** [comment]
that's hashable, sure. but I was wondering about "hashashable" ;)

**Pull request merged**
