### PR TITLE
Add description and semantic to tables

### PR DESCRIPTION
**Pull request by kayoub5**

### CODE REVIEW

**Review by andlaus — COMMENTED** [review]
looks good. before I merge this, can you addapt the somersault example ECU to include the new attributes?

**Comment by kayoub5** [comment]
> looks good. before I merge this, can you addapt the somersault example ECU to include the new attributes?

done

**Comment by andlaus** [comment]
thanks. merging

**Comment by kayoub5** [comment]
@andlaus could you publish a new version with this change?

**Comment by andlaus** [comment]
Ok. I've just created the 1.6.0 release. it should be uploaded to pypi within a few hours..

**Pull request merged**
