### PR TITLE
fix pypi packaging issues

### PR DESCRIPTION
**Pull request by ch-f**
Fix a few minor issues regarding pypi packaging just to get a smooth experience.

### CODE REVIEW

**Comment by ch-f** [comment]
The CLA-MBition@daimler.com email address does not seem to exist:

```
<[CLA-MBition@daimler.com](mailto:CLA-MBition@daimler.com)>: host one.mail-in.daimler.com[141.113.0.25] said: 550
    #5.1.0 Address rejected. (in reply to RCPT TO command)
```

**Comment by andlaus** [comment]
hm, okay. you can send it to me: andreas.lauser@mercedes-benz.com

**Comment by andlaus** [comment]
thanks for doing with the PyPI stuff, BTW...

**Comment by andlaus** [comment]
ok, I've received the CLA. Merging. Thank you!

**Pull request merged**
