### PR TITLE
Fix table row odx_id building

### PR DESCRIPTION
**Pull request by kayoub5**

### CODE REVIEW

**Comment by andlaus** [comment]
thanks for the catch. merging

**Comment by kayoub5** [comment]
@andlaus could you publish a hotfix release?

**Comment by andlaus** [comment]
not easily: the keyword-only change of #111 necessiates a 3.0 release and #117 would immediately require 4.0 after that. Can you wait until #117 is in. (hopefully tomorrow)

**Comment by kayoub5** [comment]
> not easily: the keyword-only change of #111 necessiates a 3.0 release and #117 would immediately require 4.0 after that. Can you wait until #117 is in. (hopefully tomorrow)

ok

**Pull request merged**
